imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
    tests:
        override:
            -
                command: "make phpunit --configuration phpunit.xml.dist"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
