index:
    path: /
    controller: App\Controller\DefaultController::index

app_dice_throw:
    path: /dice/throw
    controller: App\Controller\DiceController::throwDice

app_game21_play:
    path: /dice/game21/play
    controller: App\Controller\Game21Controller::playGame

app_game21_setup:
    path: /dice/game21/setup
    controller: App\Controller\Game21Controller::setup

app_game21_player_roll:
    path: /dice/game21/player_roll
    controller: App\Controller\Game21Controller::playerRoll

app_game21_computer_roll:
    path: /dice/game21/computer_roll
    controller: App\Controller\Game21Controller::computerRoll

app_game21_play_again:
    path: /dice/game21/play_again
    controller: App\Controller\Game21Controller::playAgain

app_game21_reset_score:
    path: /dice/game21/reset_score
    controller: App\Controller\Game21Controller::resetScore

app_game21_reset_bitcoins:
    path: /dice/game21/reset_bitcoins
    controller: App\Controller\Game21Controller::resetBitcoins


app_yatzy_play:
    path: /dice/yatzy/play
    controller: App\Controller\YatzyController::playGame

app_yatzy_player_roll:
    path: /dice/yatzy/player-roll
    controller: App\Controller\YatzyController::playerRoll

app_yatzy_lock_dice:
    path: /dice/yatzy/lock-dice
    controller: App\Controller\YatzyController::lockDice

app_yatzy_lock_score:
    path: /dice/yatzy/lock-score
    controller: App\Controller\YatzyController::lockScore

app_yatzy_new_game:
    path: /dice/yatzy/new-game
    controller: App\Controller\YatzyController::newGame
    

# the "app_lucky_number" route name is not important yet
#app_lucky_number:
    #path: /lucky/number
    #controller: App\Controller\LuckyController::number